//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicrosoftAzureVirtualMachineInitializer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MicrosoftAzureVirtualMachineInitializer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When manually configuring the virtual machine settings
        ///in preparation for provisioning and initialization within
        ///Microsoft Azure, it should be noted that ALL of the
        ///virtual machines will be part of the same identical
        ///virtual machine cluster (i.e. shared cluster identifier)
        ///and all of the virtual machines will be configured to
        ///use the same digital contract and the same dataset..
        /// </summary>
        internal static string Help_001 {
            get {
                return ResourceManager.GetString("Help_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MicrosoftLogo {
            get {
                object obj = ResourceManager.GetObject("MicrosoftLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;properties&quot;: {
        ///    &quot;enableAcceleratedNetworking&quot;: false,
        ///    &quot;ipConfigurations&quot;: [
        ///      {
        ///        &quot;name&quot;: &quot;{{Name}}&quot;,
        ///        &quot;properties&quot;: {
        ///          &quot;publicIPAddress&quot;: {
        ///            &quot;id&quot;: &quot;/subscriptions/{{SubscriptionId}}/resourceGroups/{{ResourceGroup}}/providers/Microsoft.Network/publicIPAddresses/{{IpAddressId}}&quot;
        ///          },
        ///          &quot;subnet&quot;: {
        ///            &quot;id&quot;: &quot;/subscriptions/{{SubscriptionId}}/resourceGroups/{{ResourceGroup}}/providers/Microsoft.Network/virtualNetworks/{{Virtua [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NetworkInterfaceJson {
            get {
                return ResourceManager.GetString("NetworkInterfaceJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;location&quot;: &quot;{{Location}}&quot;
        ///}.
        /// </summary>
        internal static string PublicIpJson {
            get {
                return ResourceManager.GetString("PublicIpJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;location&quot;: &quot;{{Location}}&quot;
        ///}.
        /// </summary>
        internal static string ResourceGroupJson {
            get {
                return ResourceManager.GetString("ResourceGroupJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SAIL_Icon {
            get {
                object obj = ResourceManager.GetObject("SAIL Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;location&quot;: &quot;{{Location}}&quot;,
        ///  &quot;properties&quot;: {
        ///    &quot;hardwareProfile&quot;: {
        ///      &quot;vmSize&quot;: &quot;Standard_D1_v2&quot;
        ///    },
        ///    &quot;storageProfile&quot;: {
        ///      &quot;imageReference&quot;: {
        ///        &quot;publisher&quot;: &quot;canonical&quot;,
        ///        &quot;offer&quot;: &quot;0001-com-ubuntu-server-focal&quot;,
        ///        &quot;sku&quot;: &quot;20_04-lts&quot;,
        ///        &quot;version&quot;: &quot;latest&quot;
        ///    },
        ///      &quot;osDisk&quot;: {
        ///        &quot;caching&quot;: &quot;ReadWrite&quot;,
        ///        &quot;managedDisk&quot;: {
        ///          &quot;storageAccountType&quot;: &quot;Standard_LRS&quot;
        ///        },
        ///        &quot;name&quot;: &quot;{{OsDiskName}}&quot;,
        ///        &quot;create [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VirtualMachineConfigurationJson {
            get {
                return ResourceManager.GetString("VirtualMachineConfigurationJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;location&quot;: &quot;{{Location}}&quot;,
        ///  &quot;plan&quot;: {
        ///    &quot;name&quot;: &quot;pro-20_04-lts&quot;,
        ///    &quot;publisher&quot;: &quot;canonical&quot;,
        ///    &quot;product&quot;: &quot;0001-com-ubuntu-pro-focal&quot;
        ///  },
        ///  &quot;properties&quot;: {
        ///    &quot;hardwareProfile&quot;: {
        ///      &quot;vmSize&quot;: &quot;{{VmSize}}&quot;
        ///    },
        ///    &quot;storageProfile&quot;: {
        ///      &quot;imageReference&quot;: {
        ///        &quot;id&quot;: &quot;/subscriptions/{{SubscriptionId}}/resourceGroups/{{ResourceGroup}}/providers/Microsoft.Compute/images/{{ImageName}}&quot;
        ///      },
        ///      &quot;osDisk&quot;: {
        ///        &quot;caching&quot;: &quot;ReadWrite&quot;,
        ///        &quot;managedDisk&quot;: { [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VirtualMachineFromImageJson {
            get {
                return ResourceManager.GetString("VirtualMachineFromImageJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;properties&quot;: {
        ///      &quot;addressSpace&quot;: {
        ///        &quot;addressPrefixes&quot;: [
        ///          &quot;10.0.0.0/16&quot;
        ///        ]
        ///      }
        ///    },
        ///    &quot;location&quot;: &quot;{{Location}}&quot;
        ///}.
        /// </summary>
        internal static string VirtualNetworkJson {
            get {
                return ResourceManager.GetString("VirtualNetworkJson", resourceCulture);
            }
        }
    }
}
